### ISSUE TITLE
Add Mun Programming Language (written in Rust) to support page

### ISSUE THREAD

**Issue by Wodann** [wezm/read-rust#104]
**Name:** Mun Programming Language
**Source Code URL:** https://github.com/mun-lang
**Support URL:** https://opencollective.com/mun
**Description:** Mun is an experimental programming language empowering creation through iteration. What started out as hot reloading experimentation is Rust, culminated in an experimental programming language trying to achieve quick developer iteration through natively supported hot reloading for data and functions. The entire toolchain will continue to be written in Rust.

**Comment by wezm** [comment]
Twitter link: https://twitter.com/wodannson/status/1178408744239161345?s=20
