### ISSUE TITLE
Add myself as creator

### ISSUE THREAD

**Issue by phansch** [wezm/read-rust#106]
Hi, I'd love to add myself to the 'Support Rust' page, if that's alright. Thanks for setting up that page! Let me know if you need more information or if I should open a PR.

**Name:** Philipp Hansch
**Source Code URL:** https://github.com/phansch
**Support URL:** https://github.com/sponsors/phansch
**Description:** Philipp is a member of the <a href="https://www.rust-lang.org/governance/teams/dev-tools#clippy">Clippy team</a> where he's mainly fixing bugs and crashes to make Clippy more fun to use. When not working on Clippy, he can be found contributing to rustc and other tools. Since 2018 this work has amounted to <a href="https://phansch.net/onehundred/rust/">over 200 pull requests</a>.

**Comment by wezm** [comment]
No worries Phil. I'll get you added over the weekend.
