### ISSUE TITLE
Maybe mention Thunderbird as an RSS field reader?

### ISSUE THREAD

**Issue by HadrienG2** [wezm/read-rust#11]
As RSS/Atom/JSON feeds are unfortunately becoming a bit of a forgotten technology these days, it might be good to tell/remind Thunderbird user that they can easily integrate them into their existing e-mail based workflow without installing any extra software.

**Comment by wezm** [comment]
> RSS/Atom/JSON feeds are unfortunately becoming a bit of a forgotten technology these days

This is part of the reason why I emphasise the feeds. Do you have any pointers to how someone using Thunderbird makes use of a feed? Is it a built in thing, just choose subscribe to feed or something like that?

**Comment by HadrienG2** [comment]
I don't remember if there was any special setup required, but all of my Thunderbird installs have a "Blogs and news" item in their side-bar. By right-clicking on it and picking the "Subscribe..." context menu item, one can copy-paste an RSS or Atom feed address, and after that Thunderbird will transparently fetch news from that feed alongside new e-mails.

EDIT: At the bottom of the Account parameters dialog, there is an "Account management" drop-down. Among the choices there is an "Add feed account" option. I suspect that I may have done that as a setup step a long time ago.

Also, I translated all strings in this Github comment from French, so don't worry if the exact names differ a bit in your version.

**Comment by wezm** [comment]
Added a link to the Thunderbird docs on adding a feed.
