### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by luizirber** [wezm/read-rust#123]
Please add this post:

**Post URL:** https://blog.luizirber.org/2019/12/01/rust-2020/
**Blog Homepage:** https://blog.luizirber.org/
**Author Name:** Luiz Irber
**Categories:** one or more of: Crates, Embedded, Games and Graphics, Getting Started, Language, Performance, Tools and Applications, Web and Network Services

Optional: This is my Rust 2020 post

**Blog RSS/Atom/JSON Feed:** https://blog.luizirber.org/feed.xml

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thanks! I've published your post.
