### ISSUE TITLE
Correction of my name

### ISSUE THREAD

**Issue by simonrw** [wezm/read-rust#124]
Hi, thank you for running and maintaining this site. I think your Rust 2020 roundup is really useful!

Unfortunately you've misspelt my name. You have "Simon Walke" but it's "Simon Walker".

It looks like your post content is in your database so I can't submit a PR. Would you mind updating this?

Thanks

**Comment by wezm** [comment]
Sorry about that. Fixed now :)

**Comment by simonrw** [comment]
That's ok, it's understandable. Thanks for making the change and for the site in general, keep up the good work!
