### ISSUE TITLE
Add post: Containerized builds for Rust on the ESP32

### ISSUE THREAD

**Issue by mtnmts** [wezm/read-rust#133]
Please add this post:

**Post URL: https://dev.to/mtnmts/containerized-builds-for-rust-on-the-esp32-e8m**
**Blog Homepage: https://github.com/mtnmts ** 
**Author Name: Matan Mates** 
**Categories: Embedded**

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thanks, this has been posted.
