### ISSUE TITLE
Add Rust 2020 post

### ISSUE THREAD

**Issue by maxdeviant** [wezm/read-rust#136]
Please add this post:

**Post URL:** https://maxdeviant.com/posts/2019/rust-2020/
**Blog Homepage:** https://maxdeviant.com/
**Author Name:** Marshall Bowers
**Categories:** Language
**Blog RSS/Atom/JSON Feed:** https://maxdeviant.com/rss.xml

**Comment by wezm** [comment]
Thanks, now posted! :incoming_envelope:
