### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by errorport** [wezm/read-rust#143]
Please add this post:

**Post URL: https://medium.com/@becsegergely/exostat-minimal-system-statusbar-a288e57fa7f6** 
**Blog Homepage: https://errorport.github.io/** 
**Author Name: Gergely B. B.** 
**Categories: Tools and Applications** one or more of: Crates, Embedded, Games and Graphics, Getting Started, Language, Performance, Tools and Applications, Web and Network Services

Optional:

**Blog RSS/Atom/JSON Feed:** 

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thanks! Posted.
