### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by jsjoeio** [wezm/read-rust#144]
Please add this post:

**Post URL:** https://joeprevite.com/contributing-to-rust-open-source
**Blog Homepage:** https://joeprevite.com/
**Author Name:** Joe Previte
**Categories:** one or more of: Getting Started

Optional:

**Blog RSS/Atom/JSON Feed:** 

Argh, I should really set this up for my blog. 

### Other Posts

I don't know if I need to submit another issue for these other blog posts. They're all the same as the info above (Getting Started) 
- https://joeprevite.com/rust-learning-plan-chapter-1-notes
- https://joeprevite.com/rust-lang-book-chapter-2-notes
- https://joeprevite.com/rust-lang-book-chapter-3-notes

Thank you for making Read Rust and considering my posts! 🙏

**Comment by wezm** [comment]
Thanks Joe. I've posted the first one. I generally only post one post per author per day so I'll trickle the others out in future updates.

**Comment by jsjoeio** [comment]
Awesome! Thank you 😄

**Comment by wezm** [comment]
Just dropped these here for me to refer to later:

Chapter 2 notes: https://twitter.com/jsjoeio/status/1239332810768302081?s=20
Chapter 3 notes: https://twitter.com/jsjoeio/status/1241195457109319681?s=20
