### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by RickNln** [wezm/read-rust#145]
Please add this post:

**Post URL: https://evrone.com/dotenv-linter** 
**Blog Homepage: https://evrone.com/cases#articles** 
**Author Name: Evrone.com** 
**Categories:** Language, Tools and Applications, Web and Network Services

**Blog RSS/Atom/JSON Feed: https://evrone.com/feed.xml**

**Comment by wezm** [comment]
Thanks! This post has been published.
