### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by oppiliappan** [wezm/read-rust#149]
Please add this post:

**Post URL:** https://peppe.rs/posts/auto-currying_rust_functions/  
**Author Name:** nerdypepper  
**Categories:** Getting Started, Language  
**Blog RSS/Atom/JSON Feed:** https://peppe.rs/index.xml  
**Tweet URL:** https://twitter.com/N3rdyP3pp3r/status/1259154018674204674  

The post is mainly about proc-macros in Rust, I hope the listed categories are accurate.

Thanks for running this site @wezm!

**Comment by wezm** [comment]
Thanks! Posted.
