### ISSUE TITLE
Add post: Learning Rust in 2020

### ISSUE THREAD

**Issue by pretzelhammer** [wezm/read-rust#150]
**Post Title:** Learning Rust in 2020
**Post URL:** https://github.com/pretzelhammer/rust-blog/blob/master/posts/learning-rust-in-2020.md
**Author Name:** pretzelhammer
**Categories:** Getting Started, Language
**Tweet URL:** https://twitter.com/pretzelhammer/status/1259897499122360322

**Comment by wezm** [comment]
Thanks! Posted.
