### ISSUE TITLE
Add post: An online book, “Writing Interpreters in Rust: a Guide”

### ISSUE THREAD

**Issue by pliniker** [wezm/read-rust#155]
Please add this post:

**Post URL: https://pliniker.github.io/post/rust-hosted-langs/** 
**Author Name: Peter Liniker** 
**Categories: Tools and Applications**
**Blog RSS/Atom/JSON Feed: https://pliniker.github.io/feed.xml** 

Thank you for your invaluable read-rust service! :bow:

**Comment by wezm** [comment]
Thanks! Sorry it took so long to post it.
