### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by Stranger6667** [wezm/read-rust#160]
Please add this post:

**Post URL:** https://dygalo.dev/blog/rust-for-a-pythonista-1/
**Author Name:** Dmitry Dygalo
**Categories:** pick one: Getting Started

Optional:

**Blog RSS/Atom/JSON Feed:** https://dygalo.dev/rss.xml

Providing a feed will help me discover new posts in the future.

If you shared your post on Twitter and/or the Mastodon/the Fediverse include links below:

**Tweet URL:** https://twitter.com/Stranger6667/status/1290642980127354886?s=20
**Mastodon URL:** -

This is the first part of a 3-chapter series - I plan to post the next one this week

**Update**: The second chapter - https://dygalo.dev/blog/rust-for-a-pythonista-2/

Thank you for your consideration!

Cheers

**Comment by wezm** [comment]
Thanks! I've posted the first in the series. I only share one article per author per day, so I'll keep this open as a reminder to share the follow up posts.

**Comment by Stranger6667** [comment]
Thank you @wezm

**Comment by wezm** [comment]
I'm going to close this (I've posted the 1st and 2nd posts). I've subscribed to your feed but feel free to open a new issue when you publish the third post.
