### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by bugzmanov** [wezm/read-rust#162]
Please add this post:

**Post URL:** https://bugzmanov.github.io/nes_ebook/index.html
**Author Name:** Rafael Bagmanov
**Categories:** pick one: Games and Graphics

Optional:

**Blog RSS/Atom/JSON Feed:** 

Providing a feed will help me discover new posts in the future.

If you shared your post on Twitter and/or the Mastodon/the Fediverse include links below:

**Tweet URL:** https://twitter.com/bugzmanov/status/1292882110559195139
**Mastodon URL:** 

Thank you and best regards.

**Comment by wezm** [comment]
Thanks! Posted.
