### ISSUE TITLE
Add post "Why Rust's Unsafe Works"

### ISSUE THREAD

**Issue by jam1garner** [wezm/read-rust#163]
Please add this post:

**Post URL:** https://jam1.re/blog/why-rusts-unsafe-works
**Author Name:** jam1garner
**Categories:** pick one: Language

Optional:

**Blog RSS/Atom/JSON Feed:** https://jam1.re/rss

Providing a feed will help me discover new posts in the future.

If you shared your post on Twitter and/or the Mastodon/the Fediverse include links below:

**Tweet URL:** https://twitter.com/jam1garner/status/1294681674324877313
**Mastodon URL:** None

**Comment by wezm** [comment]
Thanks! Posted.
