### ISSUE TITLE
Add "How I Read The Rust Programming Language" post

### ISSUE THREAD

**Issue by nickgerace** [wezm/read-rust#164]
Please add this post:

**Post URL:** https://nickgerace.dev/post/how-i-read-the-rust-programming-language
**Author Name:** [Nick Gerace](https://twitter.com/nickgeracehacks)
**Categories:** Getting Started
**Blog RSS/Atom/JSON Feed:** https://nickgerace.dev/feed.xml
**Tweet URL:** https://twitter.com/nickgeracehacks/status/1296096872579375104
**Mastodon URL:** n/a

Thank you @wezm!

**Comment by wezm** [comment]
Thanks! Posted.

**Comment by nickgerace** [comment]
Thank you! Really appreciate it @wezm
