### ISSUE TITLE
Add post - Halite III Bot Development Kit in Rust

### ISSUE THREAD

**Issue by stjepangolemac** [wezm/read-rust#166]
Hi, please add this post:

**Post URL:** https://sgolem.com/halite-iii-bot-development-kit-in-rust
**Author Name:** Stjepan Golemac
**Categories:** Crates

**Blog RSS/Atom/JSON Feed:** http://sgolem.com/api/feed.rss
**Tweet URL:** https://twitter.com/SGolemac/status/1301158184984301568

**Comment by wezm** [comment]
Thanks! Posted.
