### ISSUE TITLE
Update post URL

### ISSUE THREAD

**Issue by alexliesenfeld** [wezm/read-rust#181]
Please update the URL of the post that was added in #169.

**Post URL:** https://dev.to/alexliesenfeld/rust-http-testing-with-httpmock-2mc1 
**Author Name:** Alexander Liesenfeld
**Categories:**: Web and Network Services

**Comment by wezm** [comment]
Done. See https://readrust.net/search?q=Rust+HTTP+Testing+with+httpmock to confirm
