### ISSUE TITLE
Add "Evaluating Build Scripts in the IntelliJ Rust Plugin" post

### ISSUE THREAD

**Issue by ozkriff** [wezm/read-rust#186]
Please add this post:

**Post URL:** https://blog.jetbrains.com/rust/2022/10/24/evaluating-build-scripts-in-the-intellij-rust-plugin/
**Author Name:** [Vitaly Bragilevsky](https://blog.jetbrains.com/author/vitaly-bragilevsky-jetbrains-com)
**Categories:** Tools

**Comment by wezm** [comment]
Done 🎉

**Comment by ozkriff** [comment]
Thanks!
