### ISSUE TITLE
What Every Rust Developer Should Know About Macro Support in IDEs

### ISSUE THREAD

**Issue by ozkriff** [wezm/read-rust#187]
Please add this post:

Post URL: https://blog.jetbrains.com/rust/2022/12/05/what-every-rust-developer-should-know-about-macro-support-in-ides
Author Name: [Vitaly Bragilevsky](https://blog.jetbrains.com/author/vitaly-bragilevsky-jetbrains-com)
Categories: Tools

**Comment by wezm** [comment]
Thanks, posted.
