### ISSUE TITLE
Add CodeCrafters Rust Primer

### ISSUE THREAD

**Issue by sarupbanskota** [wezm/read-rust#194]
**Post URL:** https://app.codecrafters.io/collections/rust-primer
**Author Name:** CodeCrafters
**Categories:** Getting Started

**Comment by MinisculeGirraffe** [comment]
https://github.com/rust-lang/rustlings/pull/1760#issue-1980553494

Referencing this issue. 

It seems this person is on a marketing campaign to get their company included in many repositories.
