### ISSUE TITLE
List posts on page

### ISSUE THREAD

**Issue by killercup** [wezm/read-rust#3]
Rendering a simple HTML list with links would go a long way. Bonus points for adding a `a:visited` style so I can easily see which posts I've already read :)

**Comment by wezm** [comment]
Seems there's a few people asking for this. I'll look into adding it. I don't tamper with the link styles on the website so they will be the default blue/purple for unvisited/visited.

**Comment by wezm** [comment]
I added a list of posts to the page. It's currently in feed order, not publication date. I'll deal with that tonight. #4
