### ISSUE TITLE
RSS feeds do not appear in chronological order

### ISSUE THREAD

**Issue by sdht0** [wezm/read-rust#36]
Hi!

The RSS feed generated at https://readrust.net/all/feed.rss does not sort the posts in chronological order.
I think that is causing some issues with my feed reader Netvibes.
Can you please ensure the feeds are sorted by date?

Thanks.

**Comment by wezm** [comment]
Hi Siddhartha, 
Thanks for reporting your issue. I've changed the feeds to be sorted by `date_published`. I hope that helps.

**Comment by sdht0** [comment]
Hi Wesley,

Thanks a lot for working on this! I checked the feeds and they are now sorted, but in increasing order.
Can you please update the sorting order so that they are in reverse chronological order? That is how feeds are listed in general. Sorry I should have been explicit in the original comments.

Cheers!

**Comment by wezm** [comment]
Ok, I reversed the post order.

**Comment by sdht0** [comment]
Nice! My feed reader is working fine now.

But, there seems to be some other issue now in the RSS files. If you try to click on the RSS feed link (such as https://readrust.net/all/feed.rss), the browser tries to download the RSS as a file rather than open the feed reader (it was working fine earlier). I checked on both Firefox and Chrome. I'm not sure why and I could not spot anything in your commits.

**Comment by wezm** [comment]
I don' think the feeds downloading is a new issue, but it should be fixed. I don't think the aws-cli is setting the MIME type properly when it uploads the feeds. I'll open an issue to fix it.

**Comment by sdht0** [comment]
Ah I see. Okay then. Thanks again for looking into this.

Cheers,
Sid
