### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by RalfJung** [wezm/read-rust#43]
Please add these posts:

**Post URL:** https://www.ralfj.de/blog/2018/07/19/const.html and https://www.ralfj.de/blog/2018/07/24/pointers-and-bytes.html
**Blog Homepage:** https://www.ralfj.de/blog/
**Author Name:** Ralf Jung
**Categories:** Language

Optional:

**Blog RSS/Atom/JSON Feed:** https://www.ralfj.de/blog/categories/rust.xml

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thanks for the submission. I've been overseas and am working my way through a backlog of posts. I'll get these added soon.

**Comment by RalfJung** [comment]
Thanks :)

Is the list of feeds you are checking also somewhere in the repo?

**Comment by wezm** [comment]
There's an OPML file available at https://readrust.net/rust-blogs.opml which is generated from https://github.com/wezm/read-rust/blob/master/content/_data/rust/blogs.json However it's in need of updating. I've added #44 to remind me to do that.
