### ISSUE TITLE
Add post about C2Rust

### ISSUE THREAD

**Issue by thedataking** [wezm/read-rust#46]
Please add this post:

**Post URL:**  https://galois.com/blog/2018/08/c2rust/
**Blog Homepage:** https://galois.com/blog
**Author Name:** Eric Mertens
**Categories:** Tools and Applications, Migration.

Advance apologies if this got picked up or is scheduled to appear already. Thanks for this effort!

**Comment by wezm** [comment]
Hi thanks for the submission! This post was already published to Read Rust on 21 August: https://github.com/wezm/read-rust/commit/5c00759152e400380441e2aa005706fae0ea1831
