### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by dns2utf8** [wezm/read-rust#54]
Please add this post: Rust 2019 wish list - set non-goals

**Post URL:** https://estada.ch/2019/1/9/rust-2019-wish-list/
**Blog Homepage:** https://estada.ch/
**Author Name:** Stefan Schindler
**Categories:** one or more of: Crates, Embedded, Games and Graphics, Getting Started, Language, Performance, Tools and Applications, Web and Network Servicesv
**Blog RSS/Atom Feed:** https://estada.ch/feeds/all.atom.xml

Cheers,
Stefan

**Comment by wezm** [comment]
Thanks, will try to get this in the update tonight.

**Comment by dns2utf8** [comment]
Cool! :+1:

**Comment by dns2utf8** [comment]
Thank you!
