### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by Shnatsel** [wezm/read-rust#56]
Please add this post:

https://medium.com/@shnatsel/security-as-rust-2019-goal-6a060116ba39
**Blog Homepage:** https://medium.com/@shnatsel/ (for now; no WG blog yet)
**Author Name:** Sergey Davidoff et al.
**Categories:** one or more of: Language, Tools and Applications

Optional:

**Blog RSS/Atom/JSON Feed:** https://medium.com/feed/@Shnatsel

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thanks! Published in https://github.com/wezm/read-rust/commit/602feb1f2ae401b1323dd2fecc7fb5b4f7838770
