### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by AlokJha51** [wezm/read-rust#63]
Please add this post: Fearless Concurrency in Rust 

**Post URL:** https://blog.knoldus.com/fearless-concurrency-in-rust/
**Blog Homepage:** https://blog.knoldus.com/
**Author Name:** Alok Jha, Knoldus Inc.
**Categories:**  Getting Started, Language

**Comment by wezm** [comment]
Thank you for submitting your post. Unfortunately I've decided to not to post it to Read Rust at this time. Whilst this post does contain some general information on threads and how to create a thread in Rust I don't think it is suitable for publishing to Read Rust. For examples of Rust concurrency posts that I have posted in the past see:

* https://medium.com/@polyglot_factotum/rust-regret-less-concurrency-2238b9e53333
* http://www.squidarth.com/rc/rust/2018/06/04/rust-concurrency.html
