### ISSUE TITLE
Add Post

### ISSUE THREAD

**Issue by bishtpawan** [wezm/read-rust#68]
Please add this post:
Frame Cease-less User-Interactive Concept in Rust Programming 

**Post URL:** https://blog.knoldus.com/frame-cease-less-user-interactive-concept-in-rust-programming/
**Blog Homepage:** https://blog.knoldus.com
**Author Name:** Pawan Singh Bisht, Knoldus Inc.
**Categories:** Language

**Comment by bishtpawan** [comment]
Please add this post:
Frame Cease-less User-Interactive Concept in Rust Programming

Post URL: https://blog.knoldus.com/frame-cease-less-user-interactive-concept-in-rust-programming/
Blog Homepage: https://blog.knoldus.com
Author Name: Pawan Singh Bisht, Knoldus Inc.
Categories: Language

**Comment by wezm** [comment]
Thank you for your submission. I have read you post and decided not to post it at this time as it is mostly contains content covered in chapter 2 of the the Rust book.
