### ISSUE TITLE
My first Rust post!

### ISSUE THREAD

**Issue by amanjeev** [wezm/read-rust#71]
Please add this post:

**Post URL:** https://amanjeev.com/blog/rust-document-macro-invocations/
**Blog Homepage:** https://amanjeev.com/blog/
**Author Name:** Amanjeev Sethi
**Categories:** one or more of: Getting Started, Language, 

Optional:

**Blog RSS/Atom/JSON Feed:** https://amanjeev.com/atom.xml

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thank you! Sorry for taking so long to publish your post.
