### ISSUE TITLE
Add Post

### ISSUE THREAD

**Issue by bishtpawan** [wezm/read-rust#73]
Please add this post:
Embody System Commands in Rust Programming 

**Post URL:** https://blog.knoldus.com/embody-system-commands-in-rust-programming/
**Blog Homepage:** https://blog.knoldus.com
**Author Name:** Pawan Singh Bisht, Knoldus Inc.
**Categories:** Language

**Comment by wezm** [comment]
Thank you for your submission. I have read you post and decided not to post it at this time as it is mostly contains content covered in the Rust documentation.
