### ISSUE TITLE
Add blog post

### ISSUE THREAD

**Issue by amitayadav** [wezm/read-rust#74]
Please add this post: Combinators- A functional approach of error handling in ‘Rust

**Post URL:** https://blog.knoldus.com/combinators-a-functional-approach-of-error-handling-in-rust/
**Blog Homepage:**  https://blog.knoldus.com
**Author Name:** Amita Yadav, Knoldus Inc.
**Categories:** Getting Started, Language, Performance

**Comment by wezm** [comment]
Thank you for your submission. I have read you post and decided not to post it as it is mostly contains content covered in the Rust book and documentation.
