### ISSUE TITLE
Add Blog Post

### ISSUE THREAD

**Issue by mudit111** [wezm/read-rust#75]
Please add this post:
Welcoming RUST to the world of IoT

**Post URL:** https://blog.knoldus.com/welcoming-rust-to-the-world-of-iot/
**Blog Homepage:** https://blog.knoldus.com
**Author Name:** Mudit Chhabra, Knoldus Inc.
**Categories:** Embedded

**Comment by wezm** [comment]
Thank you for your submission. I have read you post and decided not to post it at this time as it is similar to other posts I've published previously.
