### ISSUE TITLE
Variance in Rust: An intuitive explanation

### ISSUE THREAD

**Issue by ehsanmok** [wezm/read-rust#77]
Please add this post:

**Post URL:** https://ehsanmkermani.com/2019/03/16/variance-in-rust-an-intuitive-explanation/
**Blog Homepage:** https://ehsanmkermani.com/
**Author Name:** Ehsan M. Kermani
**Categories:** one or more of:  Language

Optional:

**Blog RSS/Atom/JSON Feed:** 

Providing a feed will help with discovering new posts in the future.

**Comment by wezm** [comment]
Thanks Ehsan, I didn't see this until now but I published your post last night in fd3a71f. :)

**Comment by ehsanmok** [comment]
Great! Thank you :) Sorry I didn't see it.
