### ISSUE TITLE
Dead link 2b698c99-99e0-4fad-8716-b58dbd9c255c

### ISSUE THREAD

**Issue by ohAitch** [wezm/read-rust#78]
The article "[Deploying A Rust Server to Google App Engine with Travis CI & Docker](https://medium.com/@gallantmrgn/deploying-rust-server-to-google-app-engine-with-travis-ci-docker-b80acfce2ce5)" appears to be gone from Medium

**Comment by wezm** [comment]
@MorganGallant does this post have a new home or is it gone?
