### ISSUE TITLE
New entry for the Support Rust page

### ISSUE THREAD

**Issue by Arcterus** [wezm/read-rust#81]
These are the details for me.  The post on Reddit finally pushed me to make a Patreon account.

**Name:** Alex Lyon
**Source Code URL:** [uutils](https://github.com/uutils)
**Support URL:** [Patreon](https://www.patreon.com/arcterus)
**Description:** Alex primarily maintains the various [uutils](https://github.com/uutils) projects but also contributes occasionally to other community projects like Redox (in particular [relibc](https://gitlab.redox-os.org/redox-os/relibc)) and (rarely) the Rust standard library.

**Comment by wezm** [comment]
Awesome thank you. You've been added.
