### ISSUE TITLE
Merge mre/idiomatic-rust?

### ISSUE THREAD

**Issue by mre** [wezm/read-rust#82]
I have a feeling that you're doing a much better job maintaining this project than I do with https://github.com/mre/idiomatic-rust.
Do you think it makes sense to move the articles over to your place and create a new category called "idiomatic code" on Read Rust?
If so, feel free to copy over the contents from my repo. I can also create a PR for that if you like. 😊

**Comment by mre** [comment]
Alternatively, a website dedicated to idiomatic Rust code might be a cool thing to have, too.
We could use the same layout as for "Read Rust" and curate the list separately.
Looking forward to get your input on that.

**Comment by wezm** [comment]
Hi Matthias, seems like it would be relatively straightforward to port the page over to Read Rust. I'll look at doing it in the next few days. I'll raise a PR and add you as a reviewer when it's done. I also like your CI link checker. I may incorporate that too.
