### ISSUE TITLE
Add post

### ISSUE THREAD

**Issue by matthiasbeyer** [wezm/read-rust#83]
Please add this post:

**Blog RSS/Atom/JSON Feed:** http://imag-pim.org/index.xml
**Blog Homepage:** imag-pim.org
**Author Name:** Matthias Beyer
**Categories:** one or more of: Crates: Applications/CLI

**Comment by wezm** [comment]
Was there a specific post you want shared or did you want to make me aware of your feed? If the latter, I am subscribed :+1:

**Comment by matthiasbeyer** [comment]
The latter, I am looking for contributors and I think it is a good idea if my articles appear in the read rust feed.

My feed is rather low-volume, with less than one article per month at the moment (sadly, I would love if the project would move faster)!

**Comment by wezm** [comment]
Going to close as I'm subscribed to your feed.
