### ISSUE TITLE
RSS field does not validate

### ISSUE THREAD

**Issue by HadrienG2** [wezm/read-rust#91]
So, Thunderbird is not happy about the current RSS feed, and [points to the equally unhappy W3C feed validator](https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Freadrust.net%2Fall%2Ffeed.rss) as a reference.

It seems the `<dc:creator>` markup is what's bothering them. According to [this reference page](http://www.lowter.com/blogs/2008/2/9/rss-dccreator-author), you should add an `xmlns:dc="http://purl.org/dc/elements/1.1/"` namespace to your `<rss>` tag before using this tag.

**Comment by wezm** [comment]
Thanks for letting me know. I assumed that the rss crate would add the namespace for me. I've now added it manually. https://github.com/wezm/read-rust/commit/e594e38bde8f72e9e145d85ae9b014ff4beed3e0
