### ISSUE TITLE
Add post actix-raft announcement

### ISSUE THREAD

**Issue by thedodd** [wezm/read-rust#96]
Please add this post:

**Post URL:** https://www.reddit.com/r/rust/comments/cwfgqv/announcing_actixraft_raft_distributed_consensus/
**Blog Homepage:** https://railgun-rs.github.io/actix-raft/overview.html
**Author Name:** Anthony Dodd
**Categories:** one or more of: Crates, Tools and Applications, Web and Network Services

**Comment by wezm** [comment]
Published in 4c028c8
